#!/bin/bash

if [ "$(sudo firewall-cmd --state)" != "running" ]; then
    echo "Firewall is not running."
    sudo systemctl start firewalld
    sudo systemctl enable firewalld
    if [ "$(sudo firewall-cmd --state)" != "running" ]; then
        echo "Failed to start firewall."
        exit
    fi
    echo "Firewall is running."
fi

active_zone=$(sudo firewall-cmd --get-active-zone | head -n 1)
all_zones=$(sudo firewall-cmd --get-zones)
outside_interface=$(ip -o addr show | awk '{print $2}' | uniq | grep -v "lo")

if [[ -z "$active_zone" ]]; then
    echo "Set active zone"
    exit
fi

echo "Active Zone: $active_zone"
echo "All Zones: $all_zones"
echo "Outside Interface: $outside_interface"

echo "Is this all correct? [Y/N]"
read -r correct_input

if [[ "$correct_input" == "N" || "$correct_input" == "n" ]]; then
    echo "Outside Interface: "
    read -r outside_interface
    echo "Active Zone: "
    read -r active_zone
fi

sudo firewall-cmd --zone="$active_zone" --change-interface="$outside_interface"
sudo firewall-cmd --runtime-to-permanent

services=$(sudo firewall-cmd --zone="$active_zone" --list-service)

if [[ "$services" == *"dhcpv6-client"* ]]; then
    sudo firewall-cmd --zone="$active_zone" --remove-service=dhcpv6-client
fi

sudo firewall-cmd --runtime-to-permanent
echo "Adding port 20, 21, 22"
sudo firewall-cmd --zone=$active_zone --add-port=20/tcp --permanent
sudo firewall-cmd --zone=$active_zone --add-port=21/tcp --permanent
sudo firewall-cmd --zone=$active_zone --add-port=22/tcp --permanent
sudo firewall-cmd --runtime-to-permanent
